video_cut_interval = input('Please input video cut interval (seconds): ')
frame_rate = input('Please input video framerate: ')
node_name = input('Please input node name: ')
data_buffer_time = input('Please input data file buffer days (the number of days for data files to be stored locally before getting deleted: ')
video_buffer_time = input('Please input video buffer count (the number of video files stored locally before getting deleted): ')

with open('parameters.txt', 'w') as file:
    file.write(video_cut_interval)
    file.write('\n')
    print('Set video cut interval as:', video_cut_interval)
    file.write(frame_rate)
    file.write('\n')
    print('Set framerate as:', frame_rate)
    file.write(node_name)
    file.write('\n')
    print('Set node name as:', node_name)
    file.write(data_buffer_time)
    file.write('\n')
    print('Set data buffer time as:', data_buffer_time)
    file.write(video_buffer_time)
    print('Set video buffer time as:', video_buffer_time)